### ISSUE TITLE
Dropdown toggles change to aria-hidden in the main menu.

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#115]
Navbar dropdown menus should _not_ use `display: none;`; we can use a sr-only class as well for the toggle.

**Comment by bassettsj** [comment]
``` scss
.dropdown-menu {
 @include sr-only;
  display: block;
}

.open > .dropdown-menu {
  width: auto;
  height: auto;
  padding: 5px 0;
  margin: 2px 0 0;
  // Inherited.
  overflow: visible;
  clip: auto;
  border: 1px solid $dropdown-fallback-border; // IE8 fallback
  border: 1px solid $dropdown-border;
}

```
