### ISSUE TITLE
Checkbox alignment issue

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#20]
``` scss
table .form-type-checkbox {
  input[type=checkbox],
  input[type=radio]{
    float: none;
    margin-left: 0;
  }
}
```
