### ISSUE TITLE
Kalatheme breaks conditional visibility of Add Content Item options fieldsets

### ISSUE THREAD

**Issue by UTANdev** [drupalprojects/kalatheme#227]
I have found another way in which vanilla Kalatheme breaks vanilla Panopoly.

When adding an Add Content Item widget, you have a choice of Fields, Content, or Table as Display Types. Depending on your choice, the appropriate Settings controls will appear or disappear:
- Fields: show the Field Settings fieldset
- Content: show the Content Settings fieldset
- Table: show the Column Header dropdown

Under Kalatheme, only the Column Header dropdown behaves correctly, because it's not in a fieldset. The Field Settings and Content Settings fieldsets don't disappear because of this Kalatheme CSS override:

``` css
#modal-content .ctools-auto-submit-full-form fieldset {
  width: 48%;
  display: block !important;
}
```
