### ISSUE TITLE
Views admin labels rendering in incorrect order.

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#31]
![Screenshot of the views UI with the label rendering before the item in the admin interface](https://cloud.githubusercontent.com/assets/1218420/3307571/7029966c-f66e-11e3-9541-5376ed699518.png)

``` html
<span class="views-admin-label">Format:</span>
```

``` css
.views-display-setting .label, .views-display-setting .views-ajax-link{
display: inline-block;
float: left;
}

views-display-setting .label {
margin-right: 3pt;
}
```
