### ISSUE TITLE
Vertical Tabs: No top border

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#34]
![vertical tab with overflow being hidden](https://cloud.githubusercontent.com/assets/1218420/3308958/81347b46-f68e-11e3-84e9-5a62c762184c.png)

``` scss
.vertical-tabs-list li:first-child{
  border-top-width: 1px;
}
```
