### ISSUE TITLE
Features dependency refresh button set to transparent.

### ISSUE THREAD

**Issue by bassettsj** [drupalprojects/kalatheme#35]
``` css
/* features.css:448*/
input.form-submit.features-refresh-button {
  font-size: 0.7em;
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
  background-color: transparent;
  margin-left: 1em;
}
```
